#!/bin/bash

function composer_depends {
    for p in $(composer show -i -N)
    do
        composer depends --no-ansi $p
    done
}

function digraph {
    echo 'digraph G {'
    composer_depends | sed 's/\/\|-/_/g;'\
's/requires/->/;'\
's/(dev)//;'\
's/(.*)//;'\
's/There is no installed package depending on "\(.*\)\"\./root -> \1/'
    echo '}'
}

digraph | dot -Tpng -ograph.png

